title: Maia Ha # your name (or website title) here
logo: "images/IMG_0172.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! I'm a statistician pursuing a career in data analytics.
  <br><br>
  I am working on multiple projects in the fields of healthcare, businesses, and psychology using predictive analysis and modeling. Please check them out and let me know what you think!
  <br><br>
  <a href="https://www.linkedin.com/in/maiaha/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
