title: Mai Ha # your name (or website title) here
logo: "images/IMG_0475.jpg" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Welcome! I'm currently a healthcare coordinator, applying my statistics and business background. I'm interested in programming, psychology, and music.
  <br><br>
  I have my (edited) senior project listed for now. Check back in for new projects, coming soon!
  <br><br>
  <a href="https://www.linkedin.com/in/maiqha/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
