title: Mai Ha # your name (or website title) here
logo: "images/IMG_0475.jpg" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Aspiring data analyst with 2-year work experience in healthcare
  <br><br>
  Bachelor in Applied Statistics
  <br>
  Associate in Business Management
  <br><br>
  <a href="https://maiqha.github.io/resume/2022.08.01-Mai-Ha-resume.pdf" target="_blank">View Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/maiqha/" target="_blank">View LinkedIn Profile</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
