title: Mai Ha # your name (or website title) here
logo: "images/IMG_0475.jpg" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Aspiring data analyst with 2-year experience working in the healthcare industry. Hold a Bachelor's degree is in Applied Statistics, and an Associate's degree in Business Management.
  <br><br>
  <a href="https://www.linkedin.com/in/maiqha/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
