title: Mai Ha # your name (or website title) here
logo: "images/IMG_0172.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! I'm a business-oriented statistician pursuing a career in data. I'm currently working on my Master's in Data Analytics at GATech
  <br><br>
  My projects apply statistical modeling and predictive analysis on data from fields such as business, healthcare, and psychology. Check them out and let me know what you think!
  <br><br>
  <a href="https://www.linkedin.com/in/maiqha/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
